// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFHn0WGacIqieS7N6U7Lw7my8UKij5XQI',
    appId: '1:141595166694:web:2884b2337c5f5886e57827',
    messagingSenderId: '141595166694',
    projectId: 'gasolin-a7b482a9',
    authDomain: 'gasolin-a7b482a9.firebaseapp.com',
    storageBucket: 'gasolin-a7b482a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAboVpJt8QjG5kYsBIdtVWKxSHXuno2sns',
    appId: '1:141595166694:android:56292085934ac6a0e57827',
    messagingSenderId: '141595166694',
    projectId: 'gasolin-a7b482a9',
    storageBucket: 'gasolin-a7b482a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5-Nrzqph3oDN6lfynLoOF4sDkeeQpN18',
    appId: '1:141595166694:ios:9b6db1a304c0b518e57827',
    messagingSenderId: '141595166694',
    projectId: 'gasolin-a7b482a9',
    storageBucket: 'gasolin-a7b482a9.firebasestorage.app',
    iosBundleId: 'com.example.mygas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5-Nrzqph3oDN6lfynLoOF4sDkeeQpN18',
    appId: '1:141595166694:ios:9b6db1a304c0b518e57827',
    messagingSenderId: '141595166694',
    projectId: 'gasolin-a7b482a9',
    storageBucket: 'gasolin-a7b482a9.firebasestorage.app',
    iosBundleId: 'com.example.mygas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFHn0WGacIqieS7N6U7Lw7my8UKij5XQI',
    appId: '1:141595166694:web:b6b1f53cc2c29ee0e57827',
    messagingSenderId: '141595166694',
    projectId: 'gasolin-a7b482a9',
    authDomain: 'gasolin-a7b482a9.firebaseapp.com',
    storageBucket: 'gasolin-a7b482a9.firebasestorage.app',
  );

}